# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import uber_pb2 as uber__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in uber_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UberServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.solicitarViaje = channel.unary_unary(
                '/uber.UberService/solicitarViaje',
                request_serializer=uber__pb2.Posicion.SerializeToString,
                response_deserializer=uber__pb2.InfoAuto.FromString,
                _registered_method=True)
        self.terminarViaje = channel.unary_unary(
                '/uber.UberService/terminarViaje',
                request_serializer=uber__pb2.TerminaViajeArgs.SerializeToString,
                response_deserializer=uber__pb2.ResultadoViaje.FromString,
                _registered_method=True)
        self.estadoServicio = channel.unary_unary(
                '/uber.UberService/estadoServicio',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=uber__pb2.InfoServicio.FromString,
                _registered_method=True)


class UberServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def solicitarViaje(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def terminarViaje(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def estadoServicio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'solicitarViaje': grpc.unary_unary_rpc_method_handler(
                    servicer.solicitarViaje,
                    request_deserializer=uber__pb2.Posicion.FromString,
                    response_serializer=uber__pb2.InfoAuto.SerializeToString,
            ),
            'terminarViaje': grpc.unary_unary_rpc_method_handler(
                    servicer.terminarViaje,
                    request_deserializer=uber__pb2.TerminaViajeArgs.FromString,
                    response_serializer=uber__pb2.ResultadoViaje.SerializeToString,
            ),
            'estadoServicio': grpc.unary_unary_rpc_method_handler(
                    servicer.estadoServicio,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=uber__pb2.InfoServicio.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uber.UberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uber.UberService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UberService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def solicitarViaje(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.UberService/solicitarViaje',
            uber__pb2.Posicion.SerializeToString,
            uber__pb2.InfoAuto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def terminarViaje(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.UberService/terminarViaje',
            uber__pb2.TerminaViajeArgs.SerializeToString,
            uber__pb2.ResultadoViaje.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def estadoServicio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uber.UberService/estadoServicio',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            uber__pb2.InfoServicio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
