# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uber.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'uber.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuber.proto\x12\x04uber\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x08Posicion\x12\x0f\n\x07latitud\x18\x01 \x01(\x01\x12\x10\n\x08longitud\x18\x02 \x01(\x01\"[\n\x08InfoAuto\x12\n\n\x02id\x18\x01 \x01(\x05\x12 \n\x08posicion\x18\x02 \x01(\x0b\x32\x0e.uber.Posicion\x12\x11\n\tdistancia\x18\x03 \x01(\x01\x12\x0e\n\x06precio\x18\x04 \x01(\x01\"E\n\x10TerminaViajeArgs\x12\x0f\n\x07id_auto\x18\x01 \x01(\x05\x12 \n\x08posicion\x18\x02 \x01(\x0b\x32\x0e.uber.Posicion\"?\n\x0cInfoServicio\x12\x14\n\x0ctotal_viajes\x18\x01 \x01(\x05\x12\x19\n\x05\x61utos\x18\x02 \x03(\x0b\x32\n.uber.Auto\"H\n\x04\x41uto\x12\n\n\x02id\x18\x01 \x01(\x05\x12 \n\x08posicion\x18\x02 \x01(\x0b\x32\x0e.uber.Posicion\x12\x12\n\ndisponible\x18\x03 \x01(\x08\" \n\x0eResultadoViaje\x12\x0e\n\x06precio\x18\x01 \x01(\x01\x32\xbc\x01\n\x0bUberService\x12\x30\n\x0esolicitarViaje\x12\x0e.uber.Posicion\x1a\x0e.uber.InfoAuto\x12=\n\rterminarViaje\x12\x16.uber.TerminaViajeArgs\x1a\x14.uber.ResultadoViaje\x12<\n\x0e\x65stadoServicio\x12\x16.google.protobuf.Empty\x1a\x12.uber.InfoServiciob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uber_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSICION']._serialized_start=49
  _globals['_POSICION']._serialized_end=94
  _globals['_INFOAUTO']._serialized_start=96
  _globals['_INFOAUTO']._serialized_end=187
  _globals['_TERMINAVIAJEARGS']._serialized_start=189
  _globals['_TERMINAVIAJEARGS']._serialized_end=258
  _globals['_INFOSERVICIO']._serialized_start=260
  _globals['_INFOSERVICIO']._serialized_end=323
  _globals['_AUTO']._serialized_start=325
  _globals['_AUTO']._serialized_end=397
  _globals['_RESULTADOVIAJE']._serialized_start=399
  _globals['_RESULTADOVIAJE']._serialized_end=431
  _globals['_UBERSERVICE']._serialized_start=434
  _globals['_UBERSERVICE']._serialized_end=622
# @@protoc_insertion_point(module_scope)
