# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x05\x46\x65\x63ha\x12\x0b\n\x03\x64ia\x18\x01 \x01(\x05\x12\x0b\n\x03mes\x18\x02 \x01(\x05\x12\x0c\n\x04\x61nio\x18\x03 \x01(\x05\"B\n\x10SumaFechaRequest\x12 \n\x05\x66\x65\x63ha\x18\x01 \x01(\x0b\x32\x11.helloworld.Fecha\x12\x0c\n\x04\x64ias\x18\x02 \x01(\x05\x32\x8c\x02\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x43\n\rSayHelloAgain\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x38\n\x0esiguienteFecha\x12\x11.helloworld.Fecha\x1a\x11.helloworld.Fecha\"\x00\x12\x42\n\rsumaDiasFecha\x12\x1c.helloworld.SumaFechaRequest\x1a\x11.helloworld.Fecha\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=32
  _globals['_HELLOREQUEST']._serialized_end=60
  _globals['_HELLOREPLY']._serialized_start=62
  _globals['_HELLOREPLY']._serialized_end=91
  _globals['_FECHA']._serialized_start=93
  _globals['_FECHA']._serialized_end=140
  _globals['_SUMAFECHAREQUEST']._serialized_start=142
  _globals['_SUMAFECHAREQUEST']._serialized_end=208
  _globals['_GREETER']._serialized_start=211
  _globals['_GREETER']._serialized_end=479
# @@protoc_insertion_point(module_scope)
