# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import tiro_pb2 as tiro__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tiro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TiroAlBlancoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.dimeCentroDiana = channel.unary_unary(
                '/tiro.TiroAlBlanco/dimeCentroDiana',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tiro__pb2.Centro.FromString,
                _registered_method=True)
        self.disparaCanon = channel.unary_unary(
                '/tiro.TiroAlBlanco/disparaCanon',
                request_serializer=tiro__pb2.DisparoRequest.SerializeToString,
                response_deserializer=tiro__pb2.DisparoResponse.FromString,
                _registered_method=True)
        self.mejorDisparo = channel.unary_unary(
                '/tiro.TiroAlBlanco/mejorDisparo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tiro__pb2.MejorDisparo.FromString,
                _registered_method=True)


class TiroAlBlancoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def dimeCentroDiana(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def disparaCanon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mejorDisparo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TiroAlBlancoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'dimeCentroDiana': grpc.unary_unary_rpc_method_handler(
                    servicer.dimeCentroDiana,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tiro__pb2.Centro.SerializeToString,
            ),
            'disparaCanon': grpc.unary_unary_rpc_method_handler(
                    servicer.disparaCanon,
                    request_deserializer=tiro__pb2.DisparoRequest.FromString,
                    response_serializer=tiro__pb2.DisparoResponse.SerializeToString,
            ),
            'mejorDisparo': grpc.unary_unary_rpc_method_handler(
                    servicer.mejorDisparo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tiro__pb2.MejorDisparo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tiro.TiroAlBlanco', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tiro.TiroAlBlanco', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TiroAlBlanco(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def dimeCentroDiana(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiro.TiroAlBlanco/dimeCentroDiana',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tiro__pb2.Centro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def disparaCanon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiro.TiroAlBlanco/disparaCanon',
            tiro__pb2.DisparoRequest.SerializeToString,
            tiro__pb2.DisparoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def mejorDisparo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiro.TiroAlBlanco/mejorDisparo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tiro__pb2.MejorDisparo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
