# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tiro.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'tiro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntiro.proto\x12\x04tiro\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n\x06\x43\x65ntro\x12\r\n\x05valor\x18\x01 \x01(\x01\"C\n\x0e\x44isparoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0e\n\x06\x61ngulo\x18\x02 \x01(\x01\x12\x11\n\tvelocidad\x18\x03 \x01(\x01\"$\n\x0f\x44isparoResponse\x12\x11\n\tdistancia\x18\x01 \x01(\x01\"1\n\x0cMejorDisparo\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x11\n\tdistancia\x18\x02 \x01(\x01\x32\xc0\x01\n\x0cTiroAlBlanco\x12\x37\n\x0f\x64imeCentroDiana\x12\x16.google.protobuf.Empty\x1a\x0c.tiro.Centro\x12;\n\x0c\x64isparaCanon\x12\x14.tiro.DisparoRequest\x1a\x15.tiro.DisparoResponse\x12:\n\x0cmejorDisparo\x12\x16.google.protobuf.Empty\x1a\x12.tiro.MejorDisparob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tiro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CENTRO']._serialized_start=49
  _globals['_CENTRO']._serialized_end=72
  _globals['_DISPAROREQUEST']._serialized_start=74
  _globals['_DISPAROREQUEST']._serialized_end=141
  _globals['_DISPARORESPONSE']._serialized_start=143
  _globals['_DISPARORESPONSE']._serialized_end=179
  _globals['_MEJORDISPARO']._serialized_start=181
  _globals['_MEJORDISPARO']._serialized_end=230
  _globals['_TIROALBLANCO']._serialized_start=233
  _globals['_TIROALBLANCO']._serialized_end=425
# @@protoc_insertion_point(module_scope)
