/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "uber.h"

bool_t
xdr_Posicion (XDR *xdrs, Posicion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TipoUber (XDR *xdrs, TipoUber *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InfoAuto (XDR *xdrs, InfoAuto *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->disponible))
		 return FALSE;
	 if (!xdr_Posicion (xdrs, &objp->pos))
		 return FALSE;
	 if (!xdr_TipoUber (xdrs, &objp->tipo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tarifa))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->placas, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InfoServicio (XDR *xdrs, InfoServicio *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->viajes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->libres))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ganancia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TerminaViajeArgs (XDR *xdrs, TerminaViajeArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_Posicion (xdrs, &objp->pos_final))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->costo))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->placas, 16))
		 return FALSE;
	return TRUE;
}
