/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "uber.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
uberprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		Posicion solicitar_viaje_1_arg;
		TerminaViajeArgs terminar_viaje_1_arg;
	} argument;
	union {
		InfoAuto solicitar_viaje_1_res;
		InfoServicio estado_servicio_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case solicitar_viaje:
		_xdr_argument = (xdrproc_t) xdr_Posicion;
		_xdr_result = (xdrproc_t) xdr_InfoAuto;
		local = (bool_t (*) (char *, void *,  struct svc_req *))solicitar_viaje_1_svc;
		break;

	case terminar_viaje:
		_xdr_argument = (xdrproc_t) xdr_TerminaViajeArgs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))terminar_viaje_1_svc;
		break;

	case estado_servicio:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_InfoServicio;
		local = (bool_t (*) (char *, void *,  struct svc_req *))estado_servicio_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!uberprog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
