/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UBER_H_RPCGEN
#define _UBER_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct Posicion {
	int x;
	int y;
};
typedef struct Posicion Posicion;

enum TipoUber {
	UBER_PLANET = 0,
	UBER_XL = 1,
	UBER_BLACK = 2,
};
typedef enum TipoUber TipoUber;

struct InfoAuto {
	bool_t disponible;
	Posicion pos;
	TipoUber tipo;
	int tarifa;
	char *placas;
};
typedef struct InfoAuto InfoAuto;

struct InfoServicio {
	int viajes;
	int libres;
	int ganancia;
};
typedef struct InfoServicio InfoServicio;

struct TerminaViajeArgs {
	struct Posicion pos_final;
	int costo;
	char *placas;
};
typedef struct TerminaViajeArgs TerminaViajeArgs;

#define UBERPROG 0x20000010
#define UBERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define solicitar_viaje 1
extern  enum clnt_stat solicitar_viaje_1(Posicion *, InfoAuto *, CLIENT *);
extern  bool_t solicitar_viaje_1_svc(Posicion *, InfoAuto *, struct svc_req *);
#define terminar_viaje 2
extern  enum clnt_stat terminar_viaje_1(TerminaViajeArgs *, void *, CLIENT *);
extern  bool_t terminar_viaje_1_svc(TerminaViajeArgs *, void *, struct svc_req *);
#define estado_servicio 3
extern  enum clnt_stat estado_servicio_1(void *, InfoServicio *, CLIENT *);
extern  bool_t estado_servicio_1_svc(void *, InfoServicio *, struct svc_req *);
extern int uberprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define solicitar_viaje 1
extern  enum clnt_stat solicitar_viaje_1();
extern  bool_t solicitar_viaje_1_svc();
#define terminar_viaje 2
extern  enum clnt_stat terminar_viaje_1();
extern  bool_t terminar_viaje_1_svc();
#define estado_servicio 3
extern  enum clnt_stat estado_servicio_1();
extern  bool_t estado_servicio_1_svc();
extern int uberprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Posicion (XDR *, Posicion*);
extern  bool_t xdr_TipoUber (XDR *, TipoUber*);
extern  bool_t xdr_InfoAuto (XDR *, InfoAuto*);
extern  bool_t xdr_InfoServicio (XDR *, InfoServicio*);
extern  bool_t xdr_TerminaViajeArgs (XDR *, TerminaViajeArgs*);

#else /* K&R C */
extern bool_t xdr_Posicion ();
extern bool_t xdr_TipoUber ();
extern bool_t xdr_InfoAuto ();
extern bool_t xdr_InfoServicio ();
extern bool_t xdr_TerminaViajeArgs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UBER_H_RPCGEN */
