/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "uber.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

InfoAuto *
solicitar_viaje_1(Posicion *argp, CLIENT *clnt)
{
	static InfoAuto clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, solicitar_viaje,
		(xdrproc_t) xdr_Posicion, (caddr_t) argp,
		(xdrproc_t) xdr_InfoAuto, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
terminar_viaje_1(TerminaViajeArgs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, terminar_viaje,
		(xdrproc_t) xdr_TerminaViajeArgs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

InfoServicio *
estado_servicio_1(void *argp, CLIENT *clnt)
{
	static InfoServicio clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, estado_servicio,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_InfoServicio, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
